# Generated by Django 3.1 on 2020-08-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=48)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
                ('importance', models.IntegerField()),
                ('defunct', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
    ]
