# Generated by Django 3.1 on 2020-09-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('defunct', models.CharField(max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('private', models.IntegerField()),
                ('langmask', models.IntegerField()),
                ('password', models.CharField(max_length=16)),
                ('user_id', models.CharField(max_length=48)),
            ],
            options={
                'db_table': 'contest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('contest_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('num', models.IntegerField()),
                ('c_accepted', models.IntegerField()),
                ('c_submit', models.IntegerField()),
            ],
            options={
                'db_table': 'contest_problem',
            },
        ),
    ]
