# Generated by Django 3.1 on 2020-08-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('solution_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.TextField()),
            ],
            options={
                'db_table': 'source_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourceCodeUser',
            fields=[
                ('solution_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.TextField()),
            ],
            options={
                'db_table': 'source_code_user',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={},
        ),
    ]
