# Generated by Django 3.1 on 2020-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojauth', '0002_auto_20200814_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='language',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='volume',
            field=models.IntegerField(default=1),
        ),
    ]
