# Generated by Django 3.1 on 2020-08-16 07:22

from django.db import migrations, models
from django.utils.timezone import now as now_func


class Migration(migrations.Migration):

    dependencies = [
        ('ojauth', '0005_auto_20200816_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nick',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='reg_time',
            field=models.DateTimeField(blank=True, default=now_func()),
            preserve_default=False,
        ),
    ]
