# Generated by Django 3.1 on 2020-08-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojauth', '0006_auto_20200816_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='defunct',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
