# Generated by Django 3.1 on 2020-08-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojauth', '0007_auto_20200816_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='defunct',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
